### ISSUE TITLE
Add support for YT01 model

### ISSUE THREAD

**Issue by williamd1k0** [NaitLee/Cat-Printer#23]
I bought this model recently and ended up getting a little frustrated because the only way to use it was through a suspicious mobile app.
I will be very grateful if you can add support for this model. I can help you with any information, testing and maybe even coding.

Recommended app: (iBleem) https://play.google.com/store/apps/details?id=com.bleem.liugm

Thank you so much for working on this project.

**Comment by NaitLee** [comment]
I see it's yet another brand.
I'm gonna try [another](https://apkpure.com/fun-print/com.fun.mxw) app, because it's a) by same vendor, b) looks cleaner, c) seems made for global
You could also just try it, in the mean time while when I investigate this model.
(of course, no need if you really don't want)

off-topic: the vendor name seems means chinese pinyin "印题宝". though I don't want know further about it.

**Comment by NaitLee** [comment]
Hi, you may help me to find the Bluetooth "Characteristics" of YT01.
Use [nRF Connect](https://apkpure.com/nrf-connect-for-mobile/no.nordicsemi.android.mcp), open the printer, find it with "Scanner" and see what's inside.

(the original app has really bad UI logic)

**Comment by williamd1k0** [comment]
>(the original app has really bad UI logic)

Yeah :sweat_smile:, I've tried this "Fun Print" now and it's actually the same as iBleem with slight differences in the UI.

![Screenshot_20220504-021213](https://user-images.githubusercontent.com/10428035/166627408-c0fd9f70-832a-4939-a539-2dfa396c5686.png)

Some pics:
![IMG_20220504_021652](https://user-images.githubusercontent.com/10428035/166627542-9010f668-6340-4b9a-a0b4-6ea1460c3ad2.jpg)
![IMG_20220504_021907](https://user-images.githubusercontent.com/10428035/166627551-1dcf30aa-f7af-49fc-9692-46a9bbf4b594.jpg)

>Use [nRF Connect](https://apkpure.com/nrf-connect-for-mobile/no.nordicsemi.android.mcp), open the printer, find it with "Scanner" and see what's inside.

Ok, I will try it out.

**Comment by williamd1k0** [comment]
<details>
<summary><b>Screenshots</b></summary>

![Screenshot_20220504-024457](https://user-images.githubusercontent.com/10428035/166629116-e8d4c97d-6c51-4246-8cb3-43e23b4dae63.png)
![Screenshot_20220504-024515](https://user-images.githubusercontent.com/10428035/166629121-804ded81-f779-49d3-babc-af259c4b4eb7.png)
![Screenshot_20220504-024532](https://user-images.githubusercontent.com/10428035/166629127-cdcfcadb-205d-49a8-a8d8-a5fdf6f5d6d7.png)
![Screenshot_20220504-024537](https://user-images.githubusercontent.com/10428035/166629135-ddb28272-9b80-4239-8626-f5877b2ebca8.png)
![Screenshot_20220504-025029](https://user-images.githubusercontent.com/10428035/166629176-085215e2-eca1-403e-ba97-64fa49520e26.png)
![Screenshot_20220504-025044](https://user-images.githubusercontent.com/10428035/166629186-a431ea71-cb7b-43d0-a963-b2294c83c959.png)
![Screenshot_20220504-025055](https://user-images.githubusercontent.com/10428035/166629197-0adef066-06cd-43aa-afaf-bfe69791f9c2.png)
![Screenshot_20220504-025101](https://user-images.githubusercontent.com/10428035/166629205-0785b9bd-2d56-4ac9-b145-793ad6fe6417.png)
![Screenshot_20220504-025118](https://user-images.githubusercontent.com/10428035/166629213-2269c930-d93c-4830-866f-07b6de353e15.png)
![Screenshot_20220504-025128](https://user-images.githubusercontent.com/10428035/166629216-e53da928-7c7e-4858-ac3f-31a2a61a4a09.png)

</details>

<details>
<summary><b>Log 2022-05-04 02_47_13.txt</b></summary>

```
nRF Connect, 2022-05-04
YT01 (33:9F:3E:E3:1F:63)
V	02:45:45.750	Connecting to 33:9F:3E:E3:1F:63...
D	02:45:45.750	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE)
D	02:45:46.935	[Broadcast] Action received: android.bluetooth.device.action.ACL_CONNECTED
D	02:45:46.974	[Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	02:45:46.975	Connected to 33:9F:3E:E3:1F:63
D	02:45:46.980	wait(1600ms)
V	02:45:48.582	Discovering services...
D	02:45:48.582	gatt.discoverServices()
D	02:45:48.617	[Callback] Services discovered with status: 0
I	02:45:48.617	Services discovered
V	02:45:48.669	Generic Access (0x1800)
- Device Name [R W] (0x2A00)
Unknown Service (0000ae30-0000-1000-8000-00805f9b34fb)
- Unknown Characteristic [WNR] (0000ae01-0000-1000-8000-00805f9b34fb)
- Unknown Characteristic [N] (0000ae02-0000-1000-8000-00805f9b34fb)
   Client Characteristic Configuration (0x2902)
- Unknown Characteristic [WNR] (0000ae03-0000-1000-8000-00805f9b34fb)
- Unknown Characteristic [N] (0000ae04-0000-1000-8000-00805f9b34fb)
   Client Characteristic Configuration (0x2902)
- Unknown Characteristic [I] (0000ae05-0000-1000-8000-00805f9b34fb)
   Client Characteristic Configuration (0x2902)
- Unknown Characteristic [R W] (0000ae10-0000-1000-8000-00805f9b34fb)
Unknown Service (0000ae3a-0000-1000-8000-00805f9b34fb)
- Unknown Characteristic [WNR] (0000ae3b-0000-1000-8000-00805f9b34fb)
- Unknown Characteristic [N] (0000ae3c-0000-1000-8000-00805f9b34fb)
   Client Characteristic Configuration (0x2902)
D	02:45:48.670	gatt.setCharacteristicNotification(0000ae02-0000-1000-8000-00805f9b34fb, true)
D	02:45:48.673	gatt.setCharacteristicNotification(0000ae04-0000-1000-8000-00805f9b34fb, true)
D	02:45:48.677	gatt.setCharacteristicNotification(0000ae05-0000-1000-8000-00805f9b34fb, true)
D	02:45:48.681	gatt.setCharacteristicNotification(0000ae3c-0000-1000-8000-00805f9b34fb, true)
```

</details>

**Comment by NaitLee** [comment]
Oh thank you, it's very detailed 😄
Next step for me is to trick the app to send data, dump it & analyze.
The tool is also nRF Connect.
And I feel these steps are universal and worth to make a tutorial later 🙃

The printer is completely different, maybe including communication "magic data".
Let me gather more...

**Comment by NaitLee** [comment]
Oh, wait, Services/Characteristics UUID needs to be full.
Long tap on each entry (and sub-entry) in connected YT01 "Client", on right-top there's copy button.
Put them in a text file, and be sure to label corresponding Properties (read, write, notify, etc)
It's a repeating process, but maybe worthwhile 😉

**Comment by NaitLee** [comment]
Some side notes:

- the original app is actually in JavaScript
- it also support many other models, of their own
- the real code is in `assets` (of apk). but obfuscated
- rough stat: more than 50 js files, each is around 100kib in average. after prettify there will be 10,000 lines per file
- that doesn't mean it's better than similar things: bad naming convention, pinyin variable names & english typos, poorly managed processing logic (aka Spaghetti Code, for example using `if` everywhere for different printer models)
- above is got with minified code. just think about how's their codebase.
- the communication "magic data" is buried in these obscure code. it will take some time to dig its logic out, but our traffic dumping technique may improve efficiency
- inside, the only thing I feel good about is i18n

In order to really support all `YTXX` I think we need more people, for sharing & testing.
But I have no ability to do them all by myself 😢

I will continue slowly.

**Comment by williamd1k0** [comment]
>It's a repeating process, but maybe worthwhile 

Thanks to KDE Connect I was able to share the text directly to my PC instead of copying/pasting everything manually :sweat_smile: 

Let me know if anything is still missing.

```yaml
Generic Access:
  UUID: 0x1800
  PRIMARY SERVICE:
    Device Name:
      UUID: 0x2A00
      Properties: READ, WRITE
      Parsed value: YT01
      Raw value: (0x) 59-54-30-31, "YT01"

Unknown Service:
  UUID: 0000ae30-0000-1000-8000-00805f9b34fb
  PRIMARY SERVICE:
    Unknown Service:
      UUID: 0000ae01-0000-1000-8000-00805f9b34fb
      Properties: WRITE NO RESPONSE
    Unknown Service:
      UUID: 0000ae02-0000-1000-8000-00805f9b34fb
      Properties: NOTIFY
    Unknown Service:
      UUID: 0000ae03-0000-1000-8000-00805f9b34fb
      Properties: WRITE NO RESPONSE
    Unknown Service:
      UUID: 0000ae04-0000-1000-8000-00805f9b34fb
      Properties: NOTIFY
    Unknown Service:
      UUID: 0000ae05-0000-1000-8000-00805f9b34fb
      Properties: INDICATE
    Unknown Service:
      UUID: 0000ae10-0000-1000-8000-00805f9b34fb
      Properties: READ, WRITE
      Parsed value: (0x) 00-00-00-00
      Raw value: (0x) 00-00-00-00

Unknown Service:
  UUID: 0000ae3a-0000-1000-8000-00805f9b34fb
  PRIMARY SERVICE:
    Unknown Service:
      UUID: 0000ae3b-0000-1000-8000-00805f9b34fb
      Properties: WRITE NO RESPONSE
    Unknown Service:
      UUID: 0000ae3c-0000-1000-8000-00805f9b34fb
      Properties: NOTIFY
```
